#!/bin/sh

cd $(dirname "$0")

START_DIR="$(readlink -f .)/src"

if [ "$(uname -o)" == "Cygwin" ]; then
    START_DIR=$(cygpath -w "${START_DIR}")
fi

./run python -m unittest discover -v --start-directory="${START_DIR}" --failfast $*
