#!/bin/sh

cd $(dirname "$0")

THIS_DIR=$(readlink -f .)
START_DIR="$(readlink -f .)/src"

if [ -n "$*" ]; then
    cd ${START_DIR}/tests && ${THIS_DIR}/run python -m unittest $*
else

    if [ "$(uname -o)" == "Cygwin" ]; then
        START_DIR=$(cygpath -w "${START_DIR}")
    fi

    ./run python -m unittest discover -v --start-directory="${START_DIR}" --failfast $*
fi
